version: '3.8'

services:
  kotlin-backend-exercises:
    build:
      context: .
      dockerfile: Dockerfile
    image: kotlin-backend-exercises:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev